artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  DB_NAME: "US_VISA"
  COLLECTION_NAME: "visa_data"
  train_file_name: "train.csv"
  test_file_name: "test.csv"
  local_data_file: artifacts/data_ingestion/EasyVisa.csv



data_validation:
  root_dir: artifacts/data_validation
  train_data: artifacts/data_ingestion/train.csv
  test_data: artifacts/data_ingestion/test.csv
  drift_report_path: artifacts/data_validation/drift_report.html
  validation_status_path: artifacts/data_validation/validation_status.yml